CREATE SCHEMA organize;

use organize;


CREATE TABLE `logboek` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL,
  `last_modified` DATETIME NULL,
  `created_on` DATETIME NULL COMMENT '',
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `deletedOn` DATETIME NULL,
  PRIMARY KEY (`id`)  COMMENT '');


CREATE TABLE `logboek_entry` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '',
  `logboek` BIGINT(20) NULL COMMENT '',
  `last_modified` DATETIME NULL,
  `created_on` DATETIME NULL COMMENT '',
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `deletedOn` DATETIME NULL,
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_logboek_entry_1_idx` (`logboek` ASC)  COMMENT '',
  CONSTRAINT `fk_logboek_entry_1`
  FOREIGN KEY (`logboek`)
  REFERENCES `logboek` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

DELIMITER $$

DROP TRIGGER IF EXISTS logboek_entry_BEFORE_INSERT$$
$$
CREATE DEFINER = CURRENT_USER TRIGGER `logboek_entry_BEFORE_INSERT` BEFORE INSERT ON `logboek_entry` FOR EACH ROW
  BEGIN
    SET NEW.created_on = CURRENT_TIMESTAMP;
  END
$$
DELIMITER ;

DELIMITER $$

DROP TRIGGER IF EXISTS logboek_entry_BEFORE_UPDATE$$
$$
CREATE DEFINER = CURRENT_USER TRIGGER `logboek_entry_BEFORE_UPDATE` BEFORE UPDATE ON `logboek_entry` FOR EACH ROW
  BEGIN
    SET NEW.last_modified = CURRENT_TIMESTAMP;
  END
$$
DELIMITER ;
DELIMITER $$

DROP TRIGGER IF EXISTS logboek_BEFORE_INSERT$$
$$
CREATE DEFINER = CURRENT_USER TRIGGER `logboek_BEFORE_INSERT` BEFORE INSERT ON `logboek` FOR EACH ROW
  BEGIN
    SET NEW.created_on = CURRENT_TIMESTAMP;
  END
$$
DELIMITER ;

DELIMITER $$

DROP TRIGGER IF EXISTS logboek_BEFORE_UPDATE$$
$$
CREATE DEFINER = CURRENT_USER TRIGGER `logboek_BEFORE_UPDATE` BEFORE UPDATE ON `logboek` FOR EACH ROW
  BEGIN
    SET NEW.last_modified = CURRENT_TIMESTAMP;
  END
$$
DELIMITER ;



